-- Create groups table
create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  join_code text not null unique,
  created_at timestamp with time zone default now()
);

-- Enable RLS for groups
alter table public.groups enable row level security;

-- Seed groups data
insert into public.groups (name, join_code)
values ('Varsity', 'v123')
on conflict (join_code) do nothing;

-- Create bot_users table (using bot_users to avoid conflict with auth.users/public.users)
create table if not exists public.bot_users (
  phone_number text primary key,
  group_name text,
  created_at timestamp with time zone default now()
);

-- Enable RLS for bot_users
alter table public.bot_users enable row level security;
