-- ============================================================
-- Migration: Consolidate to teams-only (eliminate groups concept)
-- Date: 2026-02-25
-- Applied to Supabase project haicfgsgimpwnukympab
-- ============================================================

-- 1. Add join_code to teams table
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS join_code text UNIQUE;
CREATE INDEX IF NOT EXISTS teams_join_code_idx ON public.teams (join_code);

-- 2. Auto-generate join_code trigger
CREATE OR REPLACE FUNCTION public.ensure_join_code()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  IF NEW.join_code IS NULL OR NEW.join_code = '' THEN
    NEW.join_code := upper(substring(md5(random()::text) from 1 for 6));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ensure_team_join_code ON public.teams;
CREATE TRIGGER ensure_team_join_code
BEFORE INSERT OR UPDATE ON public.teams
FOR EACH ROW EXECUTE FUNCTION public.ensure_join_code();

UPDATE public.teams SET join_code = upper(substring(md5(random()::text) from 1 for 6))
WHERE join_code IS NULL OR join_code = '';

-- 3. Add is_admin to whatsapp_users
ALTER TABLE public.whatsapp_users ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false;

-- 4. Enable RLS on whatsapp_users
ALTER TABLE public.whatsapp_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access to whatsapp_users" ON public.whatsapp_users FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can read whatsapp_users" ON public.whatsapp_users FOR SELECT TO authenticated USING (true);

-- 5. Create schedule_updates table
CREATE TABLE IF NOT EXISTS public.schedule_updates (
  id bigint generated by default as identity primary key,
  group_name text not null,
  content text not null,
  created_at timestamp with time zone default now(),
  updated_by text
);
ALTER TABLE public.schedule_updates ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_schedule_updates_group ON public.schedule_updates(group_name);
CREATE POLICY "Service role full access to schedule_updates" ON public.schedule_updates FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can read schedule_updates" ON public.schedule_updates FOR SELECT TO authenticated USING (true);

-- 6. Teams INSERT policy
DROP POLICY IF EXISTS "Users can insert their own team" ON public.teams;
CREATE POLICY "Users can insert their own team" ON public.teams FOR INSERT TO authenticated
WITH CHECK (subscription_status IS DISTINCT FROM 'active' AND plan IS DISTINCT FROM 'premium');

-- 7. Functions
CREATE OR REPLACE FUNCTION public.check_team_name_exists(p_name text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_exists boolean;
BEGIN
  SELECT EXISTS(SELECT 1 FROM public.teams WHERE lower(name) = lower(p_name)) INTO v_exists;
  RETURN v_exists;
END;
$$;

CREATE OR REPLACE FUNCTION public.check_group_name_exists(p_name text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN RETURN public.check_team_name_exists(p_name); END;
$$;

GRANT EXECUTE ON FUNCTION public.check_team_name_exists(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_group_name_exists(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.add_team_admin(p_phone_number text, p_group_name text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_current_user_id uuid; v_user_team text;
BEGIN
  v_current_user_id := auth.uid();
  IF v_current_user_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  SELECT (raw_user_meta_data->>'team')::text INTO v_user_team FROM auth.users WHERE id = v_current_user_id;
  IF v_user_team IS NULL OR v_user_team = '' THEN v_user_team := p_group_name; END IF;
  IF v_user_team IS DISTINCT FROM p_group_name THEN RAISE EXCEPTION 'Unauthorized: group name does not match your team.'; END IF;
  INSERT INTO public.whatsapp_users (phone_number, group_name, is_admin) VALUES (p_phone_number, p_group_name, true)
  ON CONFLICT (phone_number) DO UPDATE SET is_admin = true, group_name = p_group_name;
  RETURN true;
END;
$$;
GRANT EXECUTE ON FUNCTION public.add_team_admin(text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.update_team_name(p_old_name text, p_new_name text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_current_user_id uuid; v_user_team text;
BEGIN
  v_current_user_id := auth.uid();
  IF v_current_user_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  SELECT (raw_user_meta_data->>'team')::text INTO v_user_team FROM auth.users WHERE id = v_current_user_id;
  IF v_user_team IS NOT NULL AND v_user_team <> '' AND v_user_team IS DISTINCT FROM p_old_name THEN
    RAISE EXCEPTION 'Unauthorized: your team does not match the old name provided.';
  END IF;
  UPDATE public.teams SET name = p_new_name WHERE name = p_old_name;
  UPDATE public.whatsapp_users SET group_name = p_new_name WHERE group_name = p_old_name;
  UPDATE public.schedule_updates SET group_name = p_new_name WHERE group_name = p_old_name;
  RETURN true;
END;
$$;
GRANT EXECUTE ON FUNCTION public.update_team_name(text, text) TO authenticated;

-- 10. Unique constraint on whatsapp_users.phone_number
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'whatsapp_users_phone_number_key' AND conrelid = 'public.whatsapp_users'::regclass) THEN
    ALTER TABLE public.whatsapp_users ADD CONSTRAINT whatsapp_users_phone_number_key UNIQUE (phone_number);
  END IF;
END; $$;
